version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: weekly
      groups:
          php-tooling:
              patterns:
                  - "squizlabs/*"
                  - "phpstan/*"
                  - "phpunit/*"
                  - "a8cteam51/*"

    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: weekly
      groups:
          linting:
              patterns:
                  - "eslint"
                  - "eslint-*"
                  - "@eslint/*"
                  - "prettier"
                  - "globals"
          types:
              patterns:
                  - "@types/*"

    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
      groups:
          actions:
              patterns:
                  - "*"
